
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry entrytotal;
	private global::Gtk.Entry entryiva;
	private global::Gtk.Entry entrysubtotal;
	private global::Gtk.Entry entryproducto3;
	private global::Gtk.Entry entryproducto2;
	private global::Gtk.Label lblsubtotal;
	private global::Gtk.Entry entryproducto1;
	private global::Gtk.Label lblproducto1;
	private global::Gtk.Label lblproducto2;
	private global::Gtk.Label lblproducto3;
	private global::Gtk.Label lbliva;
	private global::Gtk.Label lbltotal;
	private global::Gtk.Button btnlimpiar;
	private global::Gtk.Button btnfacturar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entrytotal = new global::Gtk.Entry ();
		this.entrytotal.CanFocus = true;
		this.entrytotal.Name = "entrytotal";
		this.entrytotal.IsEditable = true;
		this.entrytotal.InvisibleChar = '•';
		this.fixed1.Add (this.entrytotal);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entrytotal]));
		w1.X = 103;
		w1.Y = 215;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryiva = new global::Gtk.Entry ();
		this.entryiva.CanFocus = true;
		this.entryiva.Name = "entryiva";
		this.entryiva.IsEditable = true;
		this.entryiva.InvisibleChar = '•';
		this.fixed1.Add (this.entryiva);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryiva]));
		w2.X = 102;
		w2.Y = 179;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entrysubtotal = new global::Gtk.Entry ();
		this.entrysubtotal.CanFocus = true;
		this.entrysubtotal.Name = "entrysubtotal";
		this.entrysubtotal.IsEditable = true;
		this.entrysubtotal.InvisibleChar = '•';
		this.fixed1.Add (this.entrysubtotal);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entrysubtotal]));
		w3.X = 102;
		w3.Y = 141;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryproducto3 = new global::Gtk.Entry ();
		this.entryproducto3.CanFocus = true;
		this.entryproducto3.Name = "entryproducto3";
		this.entryproducto3.IsEditable = true;
		this.entryproducto3.InvisibleChar = '•';
		this.fixed1.Add (this.entryproducto3);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryproducto3]));
		w4.X = 101;
		w4.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryproducto2 = new global::Gtk.Entry ();
		this.entryproducto2.CanFocus = true;
		this.entryproducto2.Name = "entryproducto2";
		this.entryproducto2.IsEditable = true;
		this.entryproducto2.InvisibleChar = '•';
		this.fixed1.Add (this.entryproducto2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryproducto2]));
		w5.X = 101;
		w5.Y = 49;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblsubtotal = new global::Gtk.Label ();
		this.lblsubtotal.Name = "lblsubtotal";
		this.lblsubtotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Subtotal");
		this.fixed1.Add (this.lblsubtotal);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblsubtotal]));
		w6.X = 32;
		w6.Y = 145;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryproducto1 = new global::Gtk.Entry ();
		this.entryproducto1.CanFocus = true;
		this.entryproducto1.Name = "entryproducto1";
		this.entryproducto1.IsEditable = true;
		this.entryproducto1.InvisibleChar = '•';
		this.fixed1.Add (this.entryproducto1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryproducto1]));
		w7.X = 101;
		w7.Y = 11;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblproducto1 = new global::Gtk.Label ();
		this.lblproducto1.Name = "lblproducto1";
		this.lblproducto1.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 1");
		this.fixed1.Add (this.lblproducto1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblproducto1]));
		w8.X = 17;
		w8.Y = 14;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblproducto2 = new global::Gtk.Label ();
		this.lblproducto2.Name = "lblproducto2";
		this.lblproducto2.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 2");
		this.fixed1.Add (this.lblproducto2);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblproducto2]));
		w9.X = 18;
		w9.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblproducto3 = new global::Gtk.Label ();
		this.lblproducto3.Name = "lblproducto3";
		this.lblproducto3.LabelProp = global::Mono.Unix.Catalog.GetString ("producto 3 ");
		this.fixed1.Add (this.lblproducto3);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblproducto3]));
		w10.X = 15;
		w10.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbliva = new global::Gtk.Label ();
		this.lbliva.Name = "lbliva";
		this.lbliva.LabelProp = global::Mono.Unix.Catalog.GetString ("Iva");
		this.fixed1.Add (this.lbliva);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbliva]));
		w11.X = 67;
		w11.Y = 182;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbltotal = new global::Gtk.Label ();
		this.lbltotal.Name = "lbltotal";
		this.lbltotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total");
		this.fixed1.Add (this.lbltotal);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbltotal]));
		w12.X = 56;
		w12.Y = 218;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnlimpiar = new global::Gtk.Button ();
		this.btnlimpiar.CanFocus = true;
		this.btnlimpiar.Name = "btnlimpiar";
		this.btnlimpiar.UseUnderline = true;
		this.btnlimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.fixed1.Add (this.btnlimpiar);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnlimpiar]));
		w13.X = 287;
		w13.Y = 133;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnfacturar = new global::Gtk.Button ();
		this.btnfacturar.CanFocus = true;
		this.btnfacturar.Name = "btnfacturar";
		this.btnfacturar.UseUnderline = true;
		this.btnfacturar.Label = global::Mono.Unix.Catalog.GetString ("Facturar");
		this.fixed1.Add (this.btnfacturar);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnfacturar]));
		w14.X = 285;
		w14.Y = 90;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnlimpiar.Clicked += new global::System.EventHandler (this.OnBtnlimpiarClicked);
		this.btnfacturar.Clicked += new global::System.EventHandler (this.OnBtnfacturarClicked);
	}
}
